/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConnectionMode } from './connection-mode';


/**
 * FR-006. `extra=\"forbid\"` is FR-001\'s structural refusal of access-key input.
 */
export interface AccountCreate { 
    alias?: string | null;
    connectionMode: ConnectionMode;
    awsAccountId?: string | null;
    roleArn?: string | null;
    externalId?: string | null;
    scanRegions?: Array<string>;
}
export namespace AccountCreate {
}


