/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScanSummary } from './scan-summary';


export interface Account { 
    id: string;
    alias?: string | null;
    connectionMode: string;
    awsAccountId: string;
    roleArn?: string | null;
    scanRegions: Array<string>;
    status: string;
    /**
     * What an admin must fix; present exactly when status is failed (FR-012).
     */
    failureReason?: string | null;
    lastScan?: ScanSummary | null;
    createdAt: string;
}

