/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScanSummary } from './scan-summary';


export interface Account { 
    id: string;
    alias?: string | null;
    connectionMode: string;
    awsAccountId: string;
    roleArn?: string | null;
    scanRegions: Array<string>;
    status: string;
    lastScan?: ScanSummary | null;
    createdAt: string;
}

