/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdvisoryGapResponse } from './advisory-gap-response';


export interface AdvisoryGapList { 
    gaps: Array<AdvisoryGapResponse>;
}

