/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * FR-015a. No `id` that a decision route could take, and no state field.  The response carries nothing a client could mistake for something to act on -- it is a statement about what the platform cannot do yet, and the remedy is a release, not a click.
 */
export interface AdvisoryGapResponse { 
    resourceType: string;
    evidenceAccountId: string;
    reason: string;
    observedAt: string;
}

