/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Which agent produced a run (spec 006, FR-005).
 */
export const AgentCapability = {
    Digest: 'digest',
    Suggester: 'suggester',
    Advisor: 'advisor',
    Narrator: 'narrator'
} as const;
export type AgentCapability = typeof AgentCapability[keyof typeof AgentCapability];

