/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AgentRunResponse { 
    id: string;
    capability: string;
    status: string;
    definitionHash: string;
    costUnits: string;
    costCapUnits: string;
    failureReason?: string | null;
    startedAt: string;
    finishedAt?: string | null;
}

