/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * How a run ended (spec 006, FR-004, FR-007a).  `TRUNCATED` is not a failure. FR-004 requires a run reaching its cost cap to stop and say so, and what it already produced may still be kept -- see FR-004a, where item-wise capabilities retain validated items and whole-artifact ones discard. `FAILED` is the unreachable-model case, which FR-007a treats as an expected steady state rather than an outage.
 */
export const AgentRunStatus = {
    Succeeded: 'succeeded',
    Truncated: 'truncated',
    Failed: 'failed'
} as const;
export type AgentRunStatus = typeof AgentRunStatus[keyof typeof AgentRunStatus];

