/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgentRunResponse } from './agent-run-response';


export interface AgentRunList { 
    runs: Array<AgentRunResponse>;
}

