/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BacktestResponse { 
    trainingDays: number;
    heldOutDays: number;
    projectedValue: string;
    actualValue: string;
    absolutePercentageError?: string | null;
}

