/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BudgetOverrun } from './budget-overrun';


export interface BudgetOverrunsList { 
    overruns: Array<BudgetOverrun>;
}

