/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * One project\'s guardrail and which thresholds it has crossed.  All four crossed timestamps are exposed, not just the one that opens a finding: FR-015 makes 80% dashboard-visible precisely *because* it sends no notification, so hiding it here would leave the only warning signal with nowhere to appear.
 */
export interface Budget { 
    id: string;
    sdaId: string;
    sdaName: string;
    amountUsd: string;
    actual80CrossedAt?: string | null;
    actual100CrossedAt?: string | null;
    forecast80CrossedAt?: string | null;
    forecast100CrossedAt?: string | null;
}

