/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * One overrun finding, carrying the project it is about.  The same lifecycle fields a tag-violation finding exposes -- this is one `Finding` row, not a parallel entity, and it moves through exactly the same open/acknowledge/resolve/suppress states.
 */
export interface BudgetOverrun { 
    id: string;
    sdaId: string;
    sdaName: string;
    budgetUsd?: string | null;
    severity: string;
    status: string;
    openedAt: string;
    resolvedAt?: string | null;
    acknowledgedAt?: string | null;
    escalatedAt?: string | null;
}

