/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * FR-031-adjacent: how the platform reaches a scanned account.  Both modes are roles-only. There is deliberately no mode that accepts an access key -- Principle III forbids storing one, so it is absent from the vocabulary rather than merely discouraged.
 */
export const ConnectionMode = {
    Local: 'local',
    AssumeRole: 'assume_role'
} as const;
export type ConnectionMode = typeof ConnectionMode[keyof typeof ConnectionMode];

