/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CoverageProposalResponse { 
    id: string;
    proposalKind: string;
    resourceType: string;
    evidenceAccountId: string;
    proposedChange: { [key: string]: any; };
    reviewState: string;
    decidedAt?: string | null;
    appliedAt?: string | null;
}

