/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoverageProposalResponse } from './coverage-proposal-response';


export interface CoverageProposalList { 
    proposals: Array<CoverageProposalResponse>;
}

