/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CurrentUser { 
    userId: string;
    email: string;
    displayName?: string | null;
    /**
     * Derived from directory group membership; never stored by the platform.
     */
    role: string;
    tenantId: string;
    lastSeenAt?: string | null;
}

