/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DependencyCheck { 
    name: string;
    status: DependencyCheck.StatusEnum;
    /**
     * Never contains credentials, connection strings, or secrets (FR-046).
     */
    detailMessage?: string | null;
}
export namespace DependencyCheck {
    export const StatusEnum = {
        Healthy: 'healthy',
        Unhealthy: 'unhealthy'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


