/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DigestFigure } from './digest-figure';
import { DigestReference } from './digest-reference';


export interface DigestSection { 
    heading: string;
    body: string;
    figures?: Array<DigestFigure>;
    references?: Array<DigestReference>;
}

