/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorBody } from './error-body';


/**
 * The uniform error envelope (FR-043).  Declared as a model, not just built as a dict, so it appears in the **generated** OpenAPI document -- which FR-048 makes the binding contract. An envelope that only exists at runtime would be invisible to the generated client, leaving every consumer to hand-roll the error type.
 */
export interface ErrorEnvelope { 
    error: ErrorBody;
}

