/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorDetail } from './error-detail';


export interface ErrorBody { 
    /**
     * Stable and machine-readable. SCREAMING_SNAKE_CASE.
     */
    code: string;
    /**
     * Human-readable and safe to display. Never reveals whether a given record exists to a caller not entitled to know (FR-035).
     */
    message: string;
    /**
     * Matches the id in the structured logs for this request (FR-044).
     */
    correlationId: string;
    /**
     * Field-level detail. Present for validation failures only.
     */
    details?: Array<ErrorDetail> | null;
}

