/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResourceSummary } from './resource-summary';


export interface Finding { 
    id: string;
    resource: ResourceSummary;
    ruleKey: string;
    ruleVersion: number;
    severity: string;
    status: string;
    openedAt: string;
    resolvedAt?: string | null;
    acknowledgedAt?: string | null;
    acknowledgedBy?: string | null;
    escalatedAt?: string | null;
}

