/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Spec 003 owns the lifecycle semantics (FR-055).  These members are the schema\'s accommodation of them, not the authoritative definition. Spec 003 may extend this enum by additive migration without renegotiating the table.
 */
export const FindingStatus = {
    Open: 'open',
    Resolved: 'resolved',
    Suppressed: 'suppressed'
} as const;
export type FindingStatus = typeof FindingStatus[keyof typeof FindingStatus];

