/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResourceSummary } from './resource-summary';
import { SdaSummary } from './sda-summary';


export interface Finding { 
    id: string;
    resource?: ResourceSummary | null;
    sda?: SdaSummary | null;
    kind: string;
    ruleKey?: string | null;
    ruleVersion?: number | null;
    severity: string;
    status: string;
    openedAt: string;
    resolvedAt?: string | null;
    acknowledgedAt?: string | null;
    acknowledgedBy?: string | null;
    escalatedAt?: string | null;
}

