/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectForecasts } from './project-forecasts';


export interface ForecastList { 
    generatedAt: string;
    projects: Array<ProjectForecasts>;
}

