/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BacktestResponse } from './backtest-response';


/**
 * One kind for one project. Either a projection or the reason there is none -- never both, never neither.
 */
export interface ForecastResponse { 
    kind: string;
    insufficientHistory: boolean;
    historyDays: number;
    requiredDays: number;
    periodStart?: string | null;
    periodEnd?: string | null;
    projectedValue?: string | null;
    backtest?: BacktestResponse | null;
}

