/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GroundingRejectionResponse { 
    id: string;
    agentRunId: string;
    rejectedReference: string;
    referenceKind: string;
    rejectedAt: string;
}

