/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DependencyCheck } from './dependency-check';


export interface HealthResponse { 
    status: HealthResponse.StatusEnum;
    checks: Array<DependencyCheck>;
    correlationId: string;
    version?: string | null;
}
export namespace HealthResponse {
    export const StatusEnum = {
        Healthy: 'healthy',
        Unhealthy: 'unhealthy'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


