/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * One unused-principal recommendation, with the evidence behind it.  `evidence` travels with every flag rather than being fetched separately: this is asking a human to delete something, and a recommendation without its basis is a guess presented as a fact.
 */
export interface IamHygieneFlag { 
    id: string;
    accountId: string;
    principalType: string;
    principalIdentifier: string;
    evidence: { [key: string]: any; };
    flaggedAt: string;
    clearedAt?: string | null;
}

