/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IamHygieneFlag } from './iam-hygiene-flag';


export interface IamHygieneFlags { 
    flags: Array<IamHygieneFlag>;
}

