/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DigestSection } from './digest-section';


/**
 * FR-009/FR-010. `available` and `isEmpty` are different answers, and collapsing them would lose the distinction the digest exists to make: \"no digest has been produced\" is a platform state, \"a digest ran and found nothing notable\" is a governance result.
 */
export interface InsightDigestResponse { 
    available: boolean;
    generatedAt?: string | null;
    periodDate?: string | null;
    isEmpty: boolean;
    selectionBasis?: string | null;
    definitionHash?: string | null;
    sections?: Array<DigestSection>;
}

