/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InventoryResourceSummary { 
    id: string;
    accountId: string;
    arn: string;
    resourceType: string;
    service: string;
    region: string;
    sdaId?: string | null;
    tagStatus: string;
    ownerStatus: string;
}

