/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * One recorded attempt, whatever its outcome (spec 005, FR-013).  `recipientEmail` is null for every non-`sent` outcome -- there was no recipient, which is the point of recording the attempt at all.
 */
export interface NotificationAttempt { 
    id: string;
    cadencePoint: string;
    outcome: string;
    recipientEmail?: string | null;
    attemptedAt: string;
}

