/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OwnershipEvidence { 
    kind: string;
    cloudtrailEventId?: string | null;
    principal?: string | null;
    eventTime?: string | null;
}

