/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OwnerIdentityOverrideBody } from './owner-identity-override-body';


export interface OwnerIdentityOverridesList { 
    overrides: Array<OwnerIdentityOverrideBody>;
}

