/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UtilizationFigure } from './utilization-figure';


export interface ProjectUtilization { 
    sdaId: string | null;
    sdaName: string | null;
    utilization: UtilizationFigure;
}

