/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InventoryResourceSummary } from './inventory-resource-summary';


export interface ResourcesPage { 
    resources: Array<InventoryResourceSummary>;
    page: number;
    pageSize: number;
    totalCount: number;
}

