/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResourceDetail { 
    id: string;
    arn: string;
    resourceType: string;
    service: string;
    region: string;
    tags: { [key: string]: string; };
    detail: { [key: string]: any; };
    owner?: { [key: string]: any; } | null;
    findings: Array<{ [key: string]: any; }>;
}

