/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OwnershipEvidence } from './ownership-evidence';


export interface ResourceOwnership { 
    resourceId: string;
    ownerEmail?: string | null;
    confidence?: string | null;
    evidence?: OwnershipEvidence | null;
    attributedAt?: string | null;
}

