/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResourceSummary { 
    id: string;
    arn: string;
    resourceType: string;
    region: string;
    accountId: string;
}

