/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RightsizingRecommendationResponse } from './rightsizing-recommendation-response';


export interface RightsizingList { 
    generatedAt: string;
    recommendations: Array<RightsizingRecommendationResponse>;
    pricingNote: string;
}

