/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RightsizingRecommendationResponse { 
    resourceId: string;
    arn: string;
    resourceType: string;
    currentClass: string;
    recommendedClass: string;
    estimatedMonthlySavingUsd: string;
    evidence: { [key: string]: any; };
}

