/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * FR-004: three independent checks a rule may express, any subset of them.
 */
export interface RuleDefinition { 
    required: boolean;
    allowedValues?: Array<string> | null;
    formatPattern?: string | null;
    severity?: RuleDefinition.SeverityEnum;
}
export namespace RuleDefinition {
    export const SeverityEnum = {
        Low: 'low',
        Medium: 'medium',
        High: 'high',
        Critical: 'critical'
    } as const;
    export type SeverityEnum = typeof SeverityEnum[keyof typeof SeverityEnum];
}


