/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RuleDefinition } from './rule-definition';


export interface Rule { 
    id: string;
    key: string;
    version: number;
    enabled: boolean;
    definition: RuleDefinition;
    effectiveFrom?: string | null;
}

