/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RuleDefinition } from './rule-definition';


/**
 * No `key` field, deliberately (FR-006): an edit targets a key via the URL path, never the request body.
 */
export interface RuleUpdate { 
    definition: RuleDefinition;
    enabled?: boolean | null;
}

