/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Scan { 
    id: string;
    accountId: string;
    trigger: string;
    status: string;
    startedAt: string;
    finishedAt?: string | null;
    resourceCount?: number | null;
}

