/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SpendRecord { 
    accountId: string;
    sdaId?: string | null;
    service?: string | null;
    spendDate: string;
    amountUsd?: string | null;
    isGap: boolean;
}

