/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SpendByProject } from './spend-by-project';
import { SpendTrendPoint } from './spend-trend-point';


export interface SpendSummary { 
    totalUsd: string;
    byProject: Array<SpendByProject>;
    trend: Array<SpendTrendPoint>;
}

