/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResourceSummary } from './resource-summary';


export interface UnmatchedResourcesList { 
    resources: Array<ResourceSummary>;
}

