/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountUtilization } from './account-utilization';
import { UtilizationFigure } from './utilization-figure';
import { ProjectUtilization } from './project-utilization';


export interface UtilizationReport { 
    overall: UtilizationFigure;
    byAccount: Array<AccountUtilization>;
    byProject: Array<ProjectUtilization>;
}

