/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A utilization percentage and the population it was measured over.  `percent` is null, never 0 or 100, when nothing measurable exists -- and `used`/`provisioned` are always present so a caller can state the scope (\"2 of 4 enriched resources\") rather than implying a claim over the whole inventory (R-509).
 */
export interface UtilizationFigure { 
    used: number;
    provisioned: number;
    percent: number | null;
}

