/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Account } from '../model/models';
import { AccountCreate } from '../model/models';
import { AccountUpdate } from '../model/models';
import { AccountsList } from '../model/models';
import { ErrorEnvelope } from '../model/models';
import { ExternalIdResponse } from '../model/models';
import { HTTPValidationError } from '../model/models';
import { Scan } from '../model/models';
import { ScansList } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AccountsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Stop scanning an account without deleting its history
     * FR-009a/FR-011a. A scan already running is unaffected (FR-009b) -- this only changes &#x60;cloud_account.status&#x60;, which the next scheduler pass reads, not the in-flight execution.
     * @endpoint post /accounts/{account_id}/deactivate
     * @param accountId 
     */
    deactivateAccount(accountId: string, extraHttpRequestParams?: any): Observable<Account>;

    /**
     * Get a fresh platform-generated ExternalId ahead of cross-account registration
     * T016a. Admin only, deliberately stateless -- see module and openapi.yaml docs.
     * @endpoint post /accounts/external-id
     */
    generateExternalId(extraHttpRequestParams?: any): Observable<ExternalIdResponse>;

    /**
     * List every registered account
     * FR-010/FR-010a. All three roles may view.
     * @endpoint get /accounts
     */
    listAccounts(extraHttpRequestParams?: any): Observable<AccountsList>;

    /**
     * Retrieve an account\&#39;s scan history
     * FR-033. Any role may view, same as the accounts list itself (FR-010a) -- read access here carries no more privilege than seeing an account exists.
     * @endpoint get /accounts/{account_id}/scans
     * @param accountId 
     */
    listScanHistory(accountId: string, extraHttpRequestParams?: any): Observable<ScansList>;

    /**
     * Resume scanning a deactivated account
     * FR-009c/FR-011a. No re-registration, no re-verification -- a stale role is caught by the same scan-failure handling that covers any active account (Edge Cases), on the next scan attempt.
     * @endpoint post /accounts/{account_id}/reactivate
     * @param accountId 
     */
    reactivateAccount(accountId: string, extraHttpRequestParams?: any): Observable<Account>;

    /**
     * Register a new AWS account
     * FR-006/FR-007/FR-011a. Verifies before accepting; refuses a duplicate (FR-009).
     * @endpoint post /accounts
     * @param accountCreate 
     */
    registerAccount(accountCreate: AccountCreate, extraHttpRequestParams?: any): Observable<Account>;

    /**
     * Trigger an on-demand scan
     * FR-026/FR-026a. Operator only -- research.md R-205\&#39;s non-hierarchical-roles point, made concrete: admin\&#39;s account-management grant does not include this.
     * @endpoint post /accounts/{account_id}/scans
     * @param accountId 
     */
    triggerScan(accountId: string, extraHttpRequestParams?: any): Observable<Scan>;

    /**
     * Edit an account\&#39;s scan-region list
     * FR-008/FR-011a. Admin only. Takes effect from the next scan onward.
     * @endpoint patch /accounts/{account_id}
     * @param accountId 
     * @param accountUpdate 
     */
    updateAccountRegions(accountId: string, accountUpdate: AccountUpdate, extraHttpRequestParams?: any): Observable<Account>;

}
