export * from './accounts.service';
import { AccountsService } from './accounts.service';
export * from './accounts.serviceInterface';
export * from './identity.service';
import { IdentityService } from './identity.service';
export * from './identity.serviceInterface';
export * from './rules.service';
import { RulesService } from './rules.service';
export * from './rules.serviceInterface';
export * from './system.service';
import { SystemService } from './system.service';
export * from './system.serviceInterface';
export const APIS = [AccountsService, IdentityService, RulesService, SystemService];
