/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { BudgetsList } from '../model/models';
import { ErrorEnvelope } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface BudgetsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Every project\&#39;s budget and threshold state
     * FR-015. Any role may read. Ordered by project name, so the dashboard\&#39;s budget rows line up with its spend-by-project table rather than arriving in insertion order.
     * @endpoint get /budgets
     */
    listBudgets(extraHttpRequestParams?: any): Observable<BudgetsList>;

}
