/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { BudgetOverrunsList } from '../model/models';
import { ErrorEnvelope } from '../model/models';
import { FindingStatus } from '../model/models';
import { HTTPValidationError } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface BudgetOverrunsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Findings opened by a project exceeding its budget
     * FR-016. Most recently opened first, matching &#x60;GET /findings&#x60;\&#39;s ordering so the two lists read as one workbench rather than two conventions.
     * @endpoint get /budget-overruns
     * @param status 
     */
    listBudgetOverruns(status?: FindingStatus, extraHttpRequestParams?: any): Observable<BudgetOverrunsList>;

}
