/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ComplianceScore } from '../model/models';
import { ErrorEnvelope } from '../model/models';
import { HTTPValidationError } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ComplianceServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Retrieve an account\&#39;s compliance score
     * FR-018/FR-019/FR-019a. Any role may view (FR-030).
     * @endpoint get /accounts/{account_id}/compliance-score
     * @param accountId 
     */
    getAccountComplianceScore(accountId: string, extraHttpRequestParams?: any): Observable<ComplianceScore>;

    /**
     * Retrieve one SDA\&#39;s compliance score
     * FR-018/FR-019/FR-019a, scoped to one SDA\&#39;s resources only.
     * @endpoint get /sdas/{sda_id}/compliance-score
     * @param sdaId 
     */
    getSdaComplianceScore(sdaId: string, extraHttpRequestParams?: any): Observable<ComplianceScore>;

}
