/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AdvisoryGapList } from '../model/models';
import { CoverageProposalList } from '../model/models';
import { CoverageProposalResponse } from '../model/models';
import { ErrorEnvelope } from '../model/models';
import { ProposalDecision } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CoverageProposalsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Accept or reject a coverage proposal
     * FR-016/FR-017/FR-018. Admin only, audited, and idempotent by refusal.  An accepted proposal takes effect on the next scan with no deployment: the scan path reads accepted mappings as configuration. That is why this handler applies nothing itself -- there is no code path here that changes a cloud account, which is what keeps FR-016\&#39;s \&quot;explicit acceptance\&quot; the whole of the action (Principle IV).  A second decision on a decided proposal is a 409 rather than a silent re-apply: moving &#x60;applied_at&#x60; would make the audit trail misstate when the change took effect.
     * @endpoint post /coverage-proposals/{proposal_id}/decision
     * @param proposalId 
     * @param proposalDecision 
     */
    decideCoverageProposal(proposalId: string, proposalDecision: ProposalDecision, extraHttpRequestParams?: any): Observable<CoverageProposalResponse>;

    /**
     * Coverage gaps that need a code change and cannot be accepted
     * FR-015a. Read-only, for every role, with no sibling decision route.  The reason served here is the one the advisor determined, read back from the row it wrote. It is not re-derived at request time: the deciding input is the enrichment registry behind the connector boundary (Principle V), and an inferred reason would be the platform\&#39;s own guess presented as its finding.
     * @endpoint get /coverage-proposals/advisory-gaps
     */
    listCoverageAdvisoryGaps(extraHttpRequestParams?: any): Observable<AdvisoryGapList>;

    /**
     * Coverage gaps the platform can close as configuration
     * FR-016. Every role may read; only an admin may decide.  Decided proposals stay in the list rather than disappearing on decision -- \&quot;we looked at this and said no\&quot; is the answer FR-018 needs to be visible, otherwise a rejected gap is indistinguishable from one never detected.
     * @endpoint get /coverage-proposals
     */
    listCoverageProposals(extraHttpRequestParams?: any): Observable<CoverageProposalList>;

}
