/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorEnvelope } from '../model/models';
import { FindingStatus } from '../model/models';
import { FindingsList } from '../model/models';
import { HTTPValidationError } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface FindingsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * List findings
     * FR-014. Any role may view (FR-030). Most recently opened first.
     * @endpoint get /findings
     * @param accountId 
     * @param resourceId 
     * @param status 
     */
    listFindings(accountId?: string, resourceId?: string, status?: FindingStatus, extraHttpRequestParams?: any): Observable<FindingsList>;

}
