/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorEnvelope } from '../model/models';
import { ForecastList } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ForecastsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Per-project spend and capacity forecasts, with backtested error
     * FR-021, FR-021a, FR-022. Every project, every kind, every time -- a project with no history is listed with the not-enough-data state rather than left out.
     * @endpoint get /forecasts
     */
    listForecasts(extraHttpRequestParams?: any): Observable<ForecastList>;

}
