/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorEnvelope } from '../model/models';
import { HTTPValidationError } from '../model/models';
import { IamHygieneFlags } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface IamHygieneServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Roles, users, and keys that appear unused
     * FR-019. Active flags by default; &#x60;includeCleared&#x3D;true&#x60; returns the history too, so an admin can see that a principal was flagged and later became active again rather than wondering where a flag went.
     * @endpoint get /iam-hygiene
     * @param accountId 
     * @param includeCleared 
     */
    listIamHygieneFlags(accountId?: string, includeCleared?: boolean, extraHttpRequestParams?: any): Observable<IamHygieneFlags>;

}
