/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CurrentUser } from '../model/models';
import { ErrorEnvelope } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface IdentityServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * The signed-in caller and their resolved role
     * Any caller with exactly one resolved role may read this, and no one else.  A caller mapping to zero or multiple directory groups never reaches here — &#x60;get_principal&#x60; raises 403 first (FR-032a).
     * @endpoint get /me
     */
    getCurrentUser(extraHttpRequestParams?: any): Observable<CurrentUser>;

}
