/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AgentCapability } from '../model/models';
import { AgentRunList } from '../model/models';
import { AgentRunStatus } from '../model/models';
import { ErrorEnvelope } from '../model/models';
import { GroundingRejectionList } from '../model/models';
import { HTTPValidationError } from '../model/models';
import { InsightDigestResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface InsightsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * The most recent validated digest for this tenant
     * FR-009, FR-007a, FR-010.  Ordered by period, not by insert time: a backfill run for an older day must not displace the current digest just because it was written most recently.
     * @endpoint get /insights/digest
     */
    getInsightDigest(extraHttpRequestParams?: any): Observable<InsightDigestResponse>;

    /**
     * Agent run history, including truncated and failed runs
     * FR-005, FR-007a. Failed and truncated runs are listed alongside successful ones -- a history showing only successes would answer \&quot;is the layer working?\&quot; with \&quot;yes\&quot; whatever the truth.
     * @endpoint get /insights/runs
     * @param capability 
     * @param status 
     */
    listAgentRuns(capability?: AgentCapability, status?: AgentRunStatus, extraHttpRequestParams?: any): Observable<AgentRunList>;

    /**
     * Outputs refused before display, and what could not be validated
     * FR-006. The rejected output itself is not stored and so is not served -- keeping it would put a fabricated reference inside the platform, which is the thing the check exists to prevent. The reference that failed is enough to diagnose the rejection.
     * @endpoint get /insights/rejections
     */
    listGroundingRejections(extraHttpRequestParams?: any): Observable<GroundingRejectionList>;

}
