/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorEnvelope } from '../model/models';
import { HTTPValidationError } from '../model/models';
import { ResourceOwnership } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface OwnershipServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Retrieve a resource\&#39;s attributed owner
     * FR-020-FR-028. Any role may view (FR-030). 200 with a null &#x60;ownerEmail&#x60;/ &#x60;confidence&#x60; (not 404) when the resource exists but is queued unattributed (FR-022) -- a resource genuinely not found still 404s.
     * @endpoint get /resources/{resource_id}/owner
     * @param resourceId 
     */
    getResourceOwner(resourceId: string, extraHttpRequestParams?: any): Observable<ResourceOwnership>;

}
