/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorEnvelope } from '../model/models';
import { HTTPValidationError } from '../model/models';
import { ResourceDetail } from '../model/models';
import { ResourcesPage } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ResourcesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * One resource\&#39;s tags, owner + evidence, findings, and enrichment detail
     * FR-012. Any role may view (FR-030). Reachable even for a soft-deleted resource (data-model.md) -- only the default listing excludes those.
     * @endpoint get /resources/{resource_id}
     * @param resourceId 
     */
    getResourceDetail(resourceId: string, extraHttpRequestParams?: any): Observable<ResourceDetail>;

    /**
     * List the resource inventory, paged and filtered
     * FR-010, FR-011. Any role may view (FR-030). Excludes soft-deleted resources by default (FR-030\&#39;s own \&quot;never a row deletion\&quot; note -- a deleted resource has no governance action to take, but its detail view stays reachable directly by ID, data-model.md).
     * @endpoint get /resources
     * @param accountId 
     * @param service 
     * @param region 
     * @param sdaId 
     * @param tagStatus 
     * @param ownerStatus 
     * @param page 
     * @param pageSize 
     */
    listResources(accountId?: string, service?: string, region?: string, sdaId?: string, tagStatus?: string, ownerStatus?: string, page?: number, pageSize?: number, extraHttpRequestParams?: any): Observable<ResourcesPage>;

}
