/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorEnvelope } from '../model/models';
import { RightsizingList } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface RightsizingServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Resources provisioned larger than their measured use, with evidence
     * FR-023. A resource that is high, variable, thin on history, unenriched, already smallest, or unknown to the class ladder is simply absent -- each of those is a reason a recommendation would be a guess, and the absence is the correct output, not an error.
     * @endpoint get /rightsizing
     */
    listRightsizingRecommendations(extraHttpRequestParams?: any): Observable<RightsizingList>;

}
