/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorEnvelope } from '../model/models';
import { Rule } from '../model/models';
import { RuleCreate } from '../model/models';
import { RuleUpdate } from '../model/models';
import { RulesList } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface RulesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a new tagging rule
     * FR-001. Admin only (FR-029). Refused if the key already exists -- editing an existing key is PATCH\&#39;s job (FR-006), not a second POST.
     * @endpoint post /rules
     * @param ruleCreate 
     */
    createRule(ruleCreate: RuleCreate, extraHttpRequestParams?: any): Observable<Rule>;

    /**
     * List every tagging rule
     * FR-001-FR-004. All three roles may view (FR-030). One row per key -- the latest version, via &#x60;DISTINCT ON&#x60; ordered by version descending.
     * @endpoint get /rules
     */
    listRules(extraHttpRequestParams?: any): Observable<RulesList>;

    /**
     * Edit a tagging rule
     * FR-005/FR-006. Admin only. Creates a new version under the same key (research.md R-301) rather than mutating the existing version in place -- the edit takes effect starting with the next scan that begins after this call, never a scan already in progress (Clarifications session 2026-08-25).
     * @endpoint patch /rules/{rule_key}
     * @param ruleKey 
     * @param ruleUpdate 
     */
    updateRule(ruleKey: string, ruleUpdate: RuleUpdate, extraHttpRequestParams?: any): Observable<Rule>;

}
