/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorEnvelope } from '../model/models';
import { HTTPValidationError } from '../model/models';
import { Sda } from '../model/models';
import { SdaCreate } from '../model/models';
import { SdaUpdate } from '../model/models';
import { SdasList } from '../model/models';
import { UnmatchedResourcesList } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface SdasServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * List every registered SDA
     * FR-007. Any role may view (FR-030).
     * @endpoint get /sdas
     */
    listSdas(extraHttpRequestParams?: any): Observable<SdasList>;

    /**
     * List resources in the \&quot;No SDA\&quot; bucket
     * FR-009/FR-012. Any role may view (FR-030) -- the P1 API the P2 triage screen (FR-012) consumes; this endpoint itself is P1 since FR-009\&#39;s visibility requirement is P1.
     * @endpoint get /sdas/unmatched-resources
     * @param accountId 
     */
    listUnmatchedResources(accountId?: string, extraHttpRequestParams?: any): Observable<UnmatchedResourcesList>;

    /**
     * Register a new SDA
     * FR-007. Admin only (FR-029). Refused with 409 if the mapping overlaps an existing SDA\&#39;s (FR-010a).
     * @endpoint post /sdas
     * @param sdaCreate 
     */
    registerSda(sdaCreate: SdaCreate, extraHttpRequestParams?: any): Observable<Sda>;

    /**
     * Remove an SDA
     * FR-010b. Admin only. Never refused for having attached resources -- the &#x60;ON DELETE SET NULL&#x60; foreign key is what immediately reverts every attached resource to the \&quot;No SDA\&quot; bucket, not application code, and not deferred to the next scan (Acceptance Scenario US2.5).
     * @endpoint delete /sdas/{sda_id}
     * @param sdaId 
     */
    removeSda(sdaId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Edit an SDA\&#39;s tag-value mapping
     * FR-010. Admin only. Reclassification of matching resources happens at the next scan (Phase 7\&#39;s worker calls &#x60;sda_matching.reclassify_account_resources&#x60;), not here -- this endpoint only updates the SDA row itself.
     * @endpoint patch /sdas/{sda_id}
     * @param sdaId 
     * @param sdaUpdate 
     */
    updateSda(sdaId: string, sdaUpdate: SdaUpdate, extraHttpRequestParams?: any): Observable<Sda>;

}
