/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorEnvelope } from '../model/models';
import { HTTPValidationError } from '../model/models';
import { SpendList } from '../model/models';
import { SpendSummary } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface SpendServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Org-wide spend totals with trend, for the cost dashboard
     * FR-003, SC-002. Org-wide (no account filter) -- every registered account\&#39;s spend, rolled up.  A trend day is &#x60;null&#x60; if *any* account has a gap for that day (FR-002a) -- a conservative \&quot;this total is not the whole picture\&quot; signal, since a partial sum presented as complete would be worse than an honest null.
     * @endpoint get /spend/summary
     * @param from 
     * @param to 
     */
    getSpendSummary(from: string, to: string, extraHttpRequestParams?: any): Observable<SpendSummary>;

    /**
     * Daily spend records, optionally filtered
     * FR-001, FR-003. &#x60;sdaId&#x3D;none&#x60; filters to the \&quot;No SDA\&quot; bucket specifically -- distinct from omitting the parameter, which applies no SDA filter at all.
     * @endpoint get /spend
     * @param from 
     * @param to 
     * @param accountId 
     * @param sdaId 
     */
    listSpend(from: string, to: string, accountId?: string, sdaId?: string, extraHttpRequestParams?: any): Observable<SpendList>;

}
