/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorEnvelope } from '../model/models';
import { HealthResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface SystemServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Service and dependency health
     * Report this service\&#39;s health and that of its dependencies.
     * @endpoint get /health
     */
    getHealth(extraHttpRequestParams?: any): Observable<HealthResponse>;

}
