/**
 * CloudPulse AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorEnvelope } from '../model/models';
import { UtilizationReport } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UtilizationServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Utilization overall, per account, and per project
     * FR-018. One response carries all three levels, which is what makes the account-to-project-to-resource drill-down reachable in three steps without a request per expansion.
     * @endpoint get /utilization
     */
    getUtilization(extraHttpRequestParams?: any): Observable<UtilizationReport>;

}
